### ISSUE TITLE
Cannot redefine property: _body

### ISSUE THREAD

**Issue by robin-garnham** [newrelic/node-newrelic-koa#161] opened 2023-08-15 04:47 UTC
## Description
Getting an error when the server attempts to process any API requests

## Expected Behavior
Server to start and be able to process requests. I have downgraded to "newrelic": "^9.15.0", and it goes back to working

## Steps to Reproduce
Starting a Koa server with New Relic & Koa plugin

## Your Environment

- Node: v16.20.1
- "koa": "^2.14.2",
- "koa-body": "^6.0.1",
- "koa-cognito-middleware": "^1.4.7",
- "koa-easy-ws": "^2.1.0",
- "koa-helmet": "^7.0.2",
- "koa-router": "^12.0.0",
- "koa-static": "^5.0.0",
- "@newrelic/koa": "^7.2.0",
- "newrelic": "^10.6.2",

## Additional context

> /Users/robin/Projects/Simple-Api/node_modules/@newrelic/koa/lib/instrumentation.js:77
  Object.defineProperty(context.response, '_body', {
         ^
TypeError: Cannot redefine property: _body
    at Function.defineProperty (<anonymous>)
    at Application.wrapCreateContext (/Users/robin/ProjectsSimple-Api/node_modules/@newrelic/koa/lib/instrumentation.js:77:10)
    at Object.applyTrap [as apply] (/Users/robin/Projects/Simple-Api//node_modules/newrelic/lib/shim/shim.js:691:29)
    at Server.handleRequest (/Users/robin/Projects/Simple-Api//node_modules/koa/lib/application.js:155:24)
    at Server.emit (node:events:513:28)
    at Server.emit (node:domain:489:12)
    at LegacyContextManager.runInContext (/Users/robin/Projects/Simple-Api/node_modules/newrelic/lib/context-manager/legacy-context-manager.js:59:23)
    at Server.wrapped (/Users/robin/Projects/Simple-Api//node_modules/newrelic/lib/transaction/tracer/index.js:203:37)
    at Server.wrappedHandler (/Users/robin/Projects/Simple-Api//node_modules/newrelic/lib/instrumentation/core/http.js:193:47)
    at LegacyContextManager.runInContext (/Users/robin/Projects/Simple-Api//node_modules/newrelic/lib/context-manager/legacy-context-manager.js:59:23)
    at Server.wrapped (/Users/robin/Projects/Simple-Api//node_modules/newrelic/lib/transaction/tracer/index.js:203:37)
    at Server.wrapTransactionInvocation (/Users/robin/Projects/Simple-Api//node_modules/newrelic/lib/transaction/tracer/index.js:123:71)
    at Server.wrappedEmit [as emit] (/Users/robin/Projects/Simple-Api//node_modules/newrelic/lib/instrumentation/core/http.js:443:28)
    at parserOnIncoming (node:_http_server:998:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)

**Comment by bizob2828** [comment] 2023-08-15 15:46
@robin-garnham any chance you can provide a reproduction case for this?

**Comment by bizob2828** [comment] 2023-09-13 16:29
@robin-garnham I'm going to close this as I cannot reproduce.  If you can provide a reproduction case, please reopen and I will take a look.

**Closed as completed by bizob2828** 2023-09-13 16:29 UTC
Labels: bug, needs-triage
